- name: Deploy PHP app with Docker
  hosts: localhost
  connection: local
  gather_facts: yes
  become: yes

  tasks:
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Python Docker SDK via apt
      ansible.builtin.apt:
        name: python3-docker
        state: present

    - name: Build Docker image using shell
      ansible.builtin.shell: docker build -t my-php-app /root/devops-exercises/delivery_exercise_1

    - name: Run Docker container
      community.docker.docker_container:
        name: my-php-app
        image: my-php-app
        state: started
        ports:
          - "8080:80"
        restart_policy: unless-stopped
