version: "3.9"

services:
  db:
    image: mariadb:11
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
